docker-compose-yaml: docker-compose.yml
project: demo-nextdrupal-nextjs

environments:
  main:
    routes:
      - node:
        - "node.demo.composetheweb.com":
            tls-acme: true
            insecure: Redirect
