version: '2'
services:
  node:
    env_file:
      - .env.local
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: lagoon/node.dockerfile
    labels:
      lagoon.type: node
    volumes:
      - ./:/app:delegated
    environment:
      - LAGOON_LOCALDEV_HTTP_PORT=3000
      - LAGOON_ROUTE=http://demo-nextdrupal-nextjs.docker.amazee.io

networks:
  amazeeio-network:
    external: true
